# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test Serein on Linux with Node Nightly

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20-nightly
        uses: actions/setup-node@v3
        with:
          node-version: '20-nightly'
      - name: Install deps and link
        run: |
          npm install
          npm link
      - name: Create working directory
        run: mkdir test
      - name: "[serein] init"
        run: serein init --yes
        working-directory: ./test
      - name: "[serein] pack"
        run: serein pack
        working-directory: ./test
